version: '{build}'
image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: true

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -pre -y

assembly_info:
  patch: true

dotnet_csproj:
  patch: false

nuget:
  disable_publish_on_pr: true

before_build:
  - ps: nuget restore src/SnakeCase.JsonNet.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value

build:
  project: src/SnakeCase.JsonNet.sln
  verbosity: minimal

after_build:
  - cmd: msbuild /t:pack src\SnakeCase.JsonNet\SnakeCase.JsonNet.csproj /p:Configuration=%CONFIGURATION% /p:Version=%GitVersion_NuGetVersion%
  - cmd: nuget pack src\SnakeCase.JsonNet.Portable\SnakeCase.JsonNet.Portable.csproj -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

artifacts:
  - path: '**\SnakeCase.JsonNet*.nupkg'
    name: NuGet
 
deploy:
  - provider: Environment
    name: PreRelease Nuget Feed
    on:
      branch: master
  - provider: Environment
    name: Public Nuget Feed
    on:
      appveyor_repo_tag: true
